# @package _global_

npz_filename: ???
train_data_iter: 15000

data:
  train:
    loader:
      num_workers: 0  # Set to 0 to disable multiprocessing
      prefetch_factor: null  # Set a value or remove it if num_workers <= 0
    iterator:
      datasets:
        repeated_npz:
          filename: ${npz_filename}
          length: ${train_data_iter}

  val:
    loader:
      batch_size: 1
      num_workers: 0  # Set to 0 to disable multiprocessing
      prefetch_factor: null  # Set a value or remove it if num_workers <= 0
    iterator:
      datasets:
        repeated_npz:
          filename: ${npz_filename}
          length:  200 #must be greater than 1 for the FID computation

  test:
    loader:
      num_workers: 0  # Set to 0 to disable multiprocessing
      prefetch_factor: null  # Set a value or remove it if num_workers <= 0
    iterator:
      datasets:
        repeated_npz:
          filename: ${npz_filename}
          length: 5